# This workflow will install Python dependencies, run tests on cookiecutter and
# deploy tutorial
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actionsl

name: Deploy Tutorial

on:
  push:
    branches: [main]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Build tutorial
      run: |
        python -V
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt 
        make -C docs html
    - name: Archive tutorial build
      uses: actions/upload-artifact@v2
      with:
          name: tutorial
          path: docs/build/html/
    - name: Deploy tutorial
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
        publish_branch: gh-pages